# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'ColonelFund' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # FacebookSDK
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  
  #FirebaseSDK
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Core'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'GoogleSignIn'
  
  # BraintreeSDK
  pod 'Braintree'
  pod 'BraintreeDropIn'
  pod 'BraintreeDropIn/UIKit'
  pod 'Braintree/DataCollector'
  pod 'Braintree/PayPal'
  pod 'Braintree/Venmo'
  pod 'Braintree/Apple-Pay'
  pod 'Braintree/3D-Secure'

  # Pods for ColonelFund

  target 'ColonelFundTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ColonelFundUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

workspace 'ColonelFund'
